FROM node:22-alpine

WORKDIR /app

RUN corepack enable

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

COPY package.json pnpm-workspace.yaml turbo.json ./
COPY pnpm-lock.yaml ./
COPY apps/web ./apps/web
COPY packages/shared-types ./packages/shared-types

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @worldcupquant/web build

EXPOSE 3000

CMD ["pnpm", "--filter", "@worldcupquant/web", "start"]
